version: "3"
services:
  caddy:
    container_name: siyuan-caddy
    restart: on-failure
    networks: 
      - service-net
      - monitor-net
    image: caddy:2.1.1
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./data/caddy/data:/data"
      - "./data/caddy/config:/config"
      - "/mnt/disk1:/srv/disk1"
      - "./data/caddy/dists:/dists"
    ports: 
      - 80:80
      - 443:443
    healthcheck:
      test: curl -f http://localhost || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  lug:
    container_name: siyuan-lug
    restart: on-failure
    command: -c /config.bootstrap.yaml
    networks: 
      - service-net
    build:
      context: ./lug
      args:
        - USE_SJTUG=true
    expose:
      - 8081
      - 7001
    volumes:
      - "./lug/worker-script:/worker-script:ro"
      - "./lug/config.yaml:/config.yaml:ro"
      - "./lug/config.bootstrap.yaml:/config.bootstrap.yaml:ro"
      - "/mnt/disk1:/srv/disk1"
    healthcheck:
      test: curl -f http://localhost:7001/v1/manager/summary || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  logspout:
    container_name: logspout
    restart: on-failure
    image: gliderlabs/logspout
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    container_name: logspout
    command: syslog+tcp://${ELK_ENDPOINT}
  
  cadvisor:
    container_name: siyuan-cadvisor
    restart: on-failure
    networks: 
      - monitor-net
    image: google/cadvisor:latest
    expose:
      - 8080
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"


  nodeexporter:
    container_name: siyuan-node_exporter
    restart: on-failure
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitor-net

networks:
  service-net:
  monitor-net:
