version: "3"
services:
  caddy:
    restart: on-failure
    networks: 
      - service_net
    image: caddy:2.1.1
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./data/caddy/data:/data"
      - "./data/caddy/config:/config"
      - "/mnt:/srv"
      - "./data/caddy/dists:/dists"
    ports: 
      - 80:80
      - 443:443
    container_name: siyuan-caddy
    healthcheck:
      test: curl -f http://localhost || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  lug:
    restart: on-failure
    command: -c /config.bootstraping.yaml
    networks: 
      - service_net
    build:
      context: ./lug
      args:
        - USE_SJTUG=true
    expose:
      - 8081
      - 7001
    container_name: siyuan-lug
    volumes:
      - "./lug/worker-script:/worker-script:ro"
      - "./lug/config.yaml:/config.yaml:ro"
      - "./lug/config.bootstraping.yaml:/config.bootstraping.yaml:ro"
      - "/mnt:/srv"
    healthcheck:
      test: curl -f http://localhost:7001/v1/manager/summary || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
networks:
  service_net:
