version: "3"
services:
  caddy:
    container_name: siyuan-caddy
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    restart: on-failure
    networks: 
      - service-net
      - monitor-net
    env_file:
      - './secrets/caddy.env'
    build:
      context: ./caddy
      args:
        - USE_SJTUG=true
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./data/caddy/data:/data"
      - "./data/caddy/config:/config"
      - "/mnt/disk1:/srv/disk1"
      - "/mnt/disk2:/srv/disk2"
      - "./data/caddy/dists:/dists"
    ports: 
      - 80:80
      - 443:443
    healthcheck:
      test: curl -f http://localhost || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      options:
        max-size: "4M"
        max-file: "20"
    ulimits:
      nofile:
        soft: 80000
        hard: 120000
    mem_limit: 10G
    memswap_limit: 10G

  lug:
    container_name: siyuan-lug
    restart: on-failure
    command: -c /config.yaml
    networks: 
      - service-net
    build:
      context: ./lug
      args:
        - USE_SJTUG=true
    environment:
      - "RUST_LOG=warn"
    expose:
      - 8081
      - 7001
    volumes:
      - "./lug/worker-script:/worker-script:ro"
      - "./lug/config.yaml:/config.yaml:ro"
      - "/mnt/disk1:/srv/disk1"
      - "/mnt/disk2:/srv/disk2"
    healthcheck:
      test: curl -f http://localhost:7001/lug/v1/manager/summary || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      options:
        max-size: "4M"
        max-file: "20"
    ulimits:
      nofile:
        soft: 80000
        hard: 120000
    mem_limit: 10G
    memswap_limit: 10G
  
  logspout:
    container_name: logspout
    restart: on-failure
    image: gliderlabs/logspout
    container_name: siyuan-logspout
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    container_name: logspout
    command: syslog+tcp://siyuan-tunnel:5003
    networks:
      - tunnel-net
  
  cadvisor:
    container_name: siyuan-cadvisor
    restart: on-failure
    networks: 
      - monitor-net
    image: google/cadvisor:latest
    expose:
      - 8080
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
  
  tunnel:
    container_name: siyuan-tunnel
    restart: on-failure
    image: v2ray/official
    expose:
      - 5003
      - 5004
      - 5005
    networks:
      - tunnel-net
    volumes: 
      - "./secrets/v2ray.json:/etc/v2ray/config.json:z,ro"

  gcr-registry:
    container_name: siyuan-gcr-registry
    restart: always
    image: registry:2
    networks:
      - service-net
      - proxy-net
    expose:
      - 80
      - 5001
    volumes:
      - "./secrets/gcr-registry.yml:/etc/docker/registry/config.yml"
    environment:
      http_proxy: http://siyuan-clash:8080
      https_proxy: http://siyuan-clash:8080
      HTTP_PROXY: http://siyuan-clash:8080
      HTTPS_PROXY: http://siyuan-clash:8080

  clash:
    build:
      context: ./clash
    command: -d /etc/clash
    volumes:
      - ./secrets/clash_config.yaml:/etc/clash/config.yaml:z,ro
    networks:
      - proxy-net
    expose:
      - 8080
    container_name: siyuan-clash
    restart: always

  mirror-intel:
    build:
      context: ./mirror-intel
      args:
        - USE_SJTUG=true
    networks:
      - service-net
    expose:
      - 8000
    container_name: siyuan-mirror-intel
    restart: unless-stopped
    env_file:
      - './secrets/mirror-intel.env'
    environment:
      RUST_LOG: warn
      http_proxy: http://172.17.0.1:8080
      https_proxy: http://172.17.0.1:8080
      HTTP_PROXY: http://172.17.0.1:8080
      HTTPS_PROXY: http://172.17.0.1:8080
      NO_PROXY: s3.jcloud.sjtu.edu.cn
    logging:
      options:
        max-size: "4M"
        max-file: "20"
    ulimits:
      nofile:
        soft: 80000
        hard: 120000
    volumes:
      - "/mnt/disk2/mirror-intel-cache:/mnt/cache"

networks:
  service-net:
  monitor-net:
  tunnel-net:
  proxy-net:
