interval: 10 # Interval between pollings
loglevel: 4 # 1-5
concurrent_limit: 5
# Prometheus metrics are exposed at http://exporter_address/metrics
exporter_address: :8081

# Address where JSON API will be served
json_api:
  address: :7001

checkpoint: /data/checkpoint.json

dummy:
  oneshot_common: &oneshot_common
    retry: 5
    retry_interval: 60

repos:
  # centos
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/centos/
    interval: 25600
    path: /srv/disk1/centos
    name: centos
    no_redir_http: true
    <<: *oneshot_common
  # debian
  - type: shell_script
    script: /worker-script/ubuntu-debian-rsync.sh
    source: rsync://mirrors.kernel.org/debian/
    interval: 43200
    path: /srv/disk1/debian
    name: debian
    no_redir_http: true
    <<: *oneshot_common
  # debian-cd
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/debian-cd/
    interval: 23600
    path: /srv/disk1/debian-cd
    name: debian-cd
    <<: *oneshot_common
  # debian-security
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.security.debian.org/debian-security/
    interval: 21100
    path: /srv/disk1/debian-security
    name: debian-security
    no_redir_http: true
    <<: *oneshot_common
  # deepin
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.deepin.com/deepin/
    interval: 21900
    path: /srv/disk1/deepin
    name: deepin
    no_redir_http: true
    <<: *oneshot_common
  # deepin-cd
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.deepin.com/cdimage/
    interval: 22900
    path: /srv/disk1/deepin-cd
    name: deepin-cd
    <<: *oneshot_common
  # docker-ce
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.tuna.tsinghua.edu.cn/docker-ce/
    interval: 86400
    path: /srv/disk2/docker-ce
    name: docker-ce
    no_redir_http: true
    <<: *oneshot_common
  # fedora/linux
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://download-ib01.fedoraproject.org/fedora-enchilada/linux/
    interval: 21600
    path: /srv/disk1/fedora/linux
    name: fedora/linux
    rsync_extra_flags: --exclude "development/*" --exclude "extras/*" --exclude "*/debug/*"
    no_redir_http: true
    <<: *oneshot_common
  # fedora/epel
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/fedora-epel/
    interval: 22600
    path: /srv/disk1/fedora/epel
    name: fedora/epel
    rsync_extra_flags: --exclude "development/*" --exclude "extras/*" --exclude "*/debug/*"
    no_redir_http: true
    <<: *oneshot_common
  # fedora-secondary
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/fedora-secondary/
    interval: 23600
    path: /srv/disk1/fedora-secondary
    name: fedora-secondary
    rsync_extra_flags: --exclude "development/*" --exclude "extras/*" --exclude "*/debug/*"
    no_redir_http: true
    <<: *oneshot_common
  # linuxmint
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/linuxmint-packages/
    interval: 22600
    path: /srv/disk1/linuxmint
    name: linuxmint
    <<: *oneshot_common
  # linuxmint-cd
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/linuxmint/
    interval: 21000
    path: /srv/disk1/linuxmint-cd
    name: linuxmint-cd
    <<: *oneshot_common
  # mageia
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/mageia/
    interval: 21200
    path: /srv/disk2/mageia
    name: mageia
    rsync_extra_flags: --exclude "*/devel/*"
    <<: *oneshot_common
  # opensuse
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://fr2.rpmfind.net/linux/opensuse/
    interval: 44200 # may be wrong
    rsync_extra_flags: --exclude "history/*" --exclude "source/*" --exclude "debug/*" --exclude "ports/zsystems/*" --exclude "ports/riscv/*" --exclude "ports/update/*"
    path: /srv/disk1/opensuse
    name: opensuse
    no_redir_http: true
    <<: *oneshot_common
  # openvz
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://download.openvz.org/openvz-download
    interval: 43600 # may be wrong
    path: /srv/disk2/openvz
    name: openvz
    <<: *oneshot_common
  # remi
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://remi.mirror.karneval.cz/remi
    interval: 43000
    path: /srv/disk2/remi
    name: remi
    no_redir_http: true
    <<: *oneshot_common
  # scientific
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirror.aarnet.edu.au/pub/scientific/
    interval: 21600 # may be wrong
    path: /srv/disk2/scientific
    name: scientific
    rsync_extra_flags: --exclude "*/obsolete/*" --exclude "obsolete"
    ignore_vanish: true
    <<: *oneshot_common
  #ubuntu
  - type: shell_script
    script: /worker-script/ubuntu-debian-rsync.sh
    source: rsync://archive.ubuntu.com/ubuntu/
    interval: 24900
    path: /srv/disk2/ubuntu
    name: ubuntu
    no_redir_http: true
    <<: *oneshot_common
  # ubuntu-cd
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.releases.ubuntu.com/releases/
    interval: 24600
    path: /srv/disk2/ubuntu-cd
    name: ubuntu-cd
    <<: *oneshot_common
  # ubuntu-cdimage
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://cdimage.ubuntu.com/cdimage/
    interval: 24900
    path: /srv/disk2/ubuntu-cdimage
    name: ubuntu-cdimage
    <<: *oneshot_common
  # ubuntu-ports
  - type: shell_script
    script: /worker-script/ubuntu-debian-rsync.sh
    source: rsync://ports.ubuntu.com/ubuntu-ports/
    interval: 31000
    path: /srv/disk2/ubuntu-ports
    name: ubuntu-ports
    no_redir_http: true
    <<: *oneshot_common
  # openwrt
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://downloads.openwrt.org/downloads/
    interval: 24900
    path: /srv/disk1/openwrt
    rsync_extra_flags: --exclude "index.html" --exclude "snapshots/*"
    name: openwrt
    no_redir_http: true
    <<: *oneshot_common
  # rpmfusion
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirror.de.leaseweb.net/rpmfusion/
    interval: 32000
    path: /srv/disk1/rpmfusion
    name: rpmfusion
    no_redir_http: true
    <<: *oneshot_common
  # homebrew-bottles
  - type: shell_script
    script: /app/mirror-clone --concurrent_resolve 128 --workers 8 homebrew_bottles --target http://siyuan-mirror-intel:8000/homebrew-bottles
    mirror_intel: true
    interval: 10800
    name: homebrew-bottles
    <<: *oneshot_common
  # rust-static
  - type: shell_script
    script: /app/mirror-clone --concurrent_resolve 64 --workers 8 rustup --target http://siyuan-mirror-intel:8000/rust-static
    mirror_intel: true
    interval: 4800
    name: rust-static
    <<: *oneshot_common
  # pypi
  - type: shell_script
    script: /app/mirror-clone --concurrent_resolve 64 --workers 16 pypi --target http://siyuan-mirror-intel:8000/pypi-packages
    mirror_intel: true
    interval: 86400
    name: pypi-packages
    <<: *oneshot_common
  # dart-pub
  - type: shell_script
    script: /app/mirror-clone --concurrent_resolve 64 --workers 8 dart_pub --target http://siyuan-mirror-intel:8000/dart-pub
    mirror_intel: true
    interval: 4800
    name: dart-pub
    <<: *oneshot_common
  # pytorch-wheels
  - type: shell_script
    script: /app/mirror-clone --concurrent_resolve 64 --workers 8 pytorch_wheels --target http://siyuan-mirror-intel:8000/pytorch-wheels
    mirror_intel: true
    interval: 4900
    name: pytorch-wheels
    <<: *oneshot_common
  # crates.io
  - type: shell_script
    script: /app/mirror-clone --concurrent_resolve 64 --workers 8 crates_io --target http://siyuan-mirror-intel:8000/crates.io/crates
    mirror_intel: true
    interval: 7200
    name: crates.io
    <<: *oneshot_common
  # flutter_infra
  - type: shell_script
    script: /app/mirror-clone --concurrent_resolve 64 --workers 8 flutter_infra --target http://siyuan-mirror-intel:8000/flutter_infra
    mirror_intel: true
    interval: 4000
    name: flutter_infra
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/git.sh
    interval: 3600
    name: git/linuxbrew-core.git
    source: https://github.com/Homebrew/linuxbrew-core.git
    path: /srv/disk2/git/linuxbrew-core.git
    target: https://git.sjtu.edu.cn/sjtug/linuxbrew-core.git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/git.sh
    interval: 3601
    name: git/homebrew-services.git
    source: https://github.com/Homebrew/homebrew-services.git
    path: /srv/disk2/git/homebrew-services.git
    target: https://git.sjtu.edu.cn/sjtug/homebrew-services.git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/git.sh
    interval: 3602
    name: git/homebrew-cask-drivers.git
    source: https://github.com/Homebrew/homebrew-cask-drivers.git
    path: /srv/disk2/git/homebrew-cask-drivers.git
    target: https://git.sjtu.edu.cn/sjtug/homebrew-cask-drivers.git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/git.sh
    interval: 3603
    name: git/homebrew-cask-fonts.git
    source: https://github.com/Homebrew/homebrew-cask-fonts.git
    path: /srv/disk2/git/homebrew-cask-fonts.git
    target: https://git.sjtu.edu.cn/sjtug/homebrew-cask-fonts.git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/git.sh
    interval: 3604
    name: git/homebrew-cask-versions.git
    source: https://github.com/Homebrew/homebrew-cask-versions.git
    path: /srv/disk2/git/homebrew-cask-versions.git
    target: https://git.sjtu.edu.cn/sjtug/homebrew-cask-versions.git
    <<: *oneshot_common
  - type: shell_script
    script: /app/mirror-clone --concurrent_resolve 128 --workers 8 homebrew_bottles --arch x86_64_linux --api_base https://formulae.brew.sh/api/formula-linux.json --target http://siyuan-mirror-intel:8000/linuxbrew-bottles
    mirror_intel: true
    interval: 10800
    name: linuxbrew-bottles
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/git.sh
    interval: 3608
    name: git/guix.git
    source: https://git.savannah.gnu.org/git/guix.git
    path: /srv/disk2/git/guix.git
    target: https://git.sjtu.edu.cn/sjtug/guix.git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/git.sh
    interval: 3700
    name: git/llvm-project.git
    source: https://github.com/llvm/llvm-project.git
    path: /srv/disk2/git/llvm-project.git
    target: https://git.sjtu.edu.cn/sjtug/llvm-project.git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/git.sh
    interval: 3650
    name: git/flutter-sdk.git
    source: https://github.com/flutter/flutter.git
    path: /srv/disk2/git/flutter-sdk.git
    target: https://git.sjtu.edu.cn/sjtug/flutter-sdk.git
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.apache.org/apache-dist/
    interval: 7200
    path: /srv/disk2/apache
    name: apache
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/git.sh
    interval: 1800
    name: git/ohmyzsh.git
    source: https://github.com/ohmyzsh/ohmyzsh.git
    path: /srv/disk2/git/ohmyzsh.git
    target: https://git.sjtu.edu.cn/sjtug/ohmyzsh.git
  - type: shell_script
    script: /worker-script/git.sh
    interval: 1900
    name: git/spacemacs.git
    source: https://github.com/syl20bnr/spacemacs.git
    path: /srv/disk2/git/spacemacs.git
    target: https://git.sjtu.edu.cn/sjtug/spacemacs.git
  - type: shell_script
    script: /worker-script/git.sh
    interval: 2000
    name: git/doom-emacs.git
    source: https://github.com/hlissner/doom-emacs.git
    path: /srv/disk2/git/doom-emacs.git
    target: https://git.sjtu.edu.cn/sjtug/doom-emacs.git
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://ftp.jaist.ac.jp/pub/DragonFly/iso-images/
    interval: 25600
    path: /srv/disk2/dragonflybsd/iso-images
    name: dragonflybsd/iso-images
    rsync_extra_flags: --exclude "tmp"
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://ftp.jaist.ac.jp/pub/DragonFly/dports/
    interval: 25600
    path: /srv/disk2/dragonflybsd/dports
    name: dragonflybsd/dports
    <<: *oneshot_common
  - type: shell_script
    name: archlinux
    path: /srv/disk2/archlinux
    interval: 3600
    disabled: true
    script: "true"
    target: https://mirrors.sjtug.sjtu.edu.cn/archlinux
    <<: *oneshot_common
  # GitHub Release (which only include FreeCAD for now)
  - type: shell_script
    script: /app/mirror-clone --concurrent_resolve 128 --workers 8 github_release --target http://siyuan-mirror-intel:8000/github-release
    mirror_intel: true
    interval: 3600
    name: github-release
    <<: *oneshot_common
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://www.blackarch.org/blackarch/
    interval: 20000
    path: /srv/disk2/blackarch
    name: blackarch
    <<: *oneshot_common
