interval: 10 # Interval between pollings
loglevel: 4 # 1-5
concurrent_limit: 5
# Prometheus metrics are exposed at http://exporter_address/metrics
exporter_address: :8081

# Address where JSON API will be served
json_api:
  address: :7001

dummy:
  oneshot_common: &oneshot_common
    retry: 5
    retry_interval: 60

repos:
  # centos
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/centos/
    interval: 25600
    path: /srv/disk1/centos
    name: centos
    <<: *oneshot_common
  # debian
  - type: shell_script
    script: /worker-script/ubuntu-debian-rsync.sh
    source: rsync://mirrors.kernel.org/debian/
    interval: 43200
    path: /srv/disk1/debian
    name: debian
    no_redir_http: true
    <<: *oneshot_common
  # debian-cd
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/debian-cd/
    interval: 23600
    path: /srv/disk1/debian-cd
    name: debian-cd
    <<: *oneshot_common
  # debian-security
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.security.debian.org/debian-security/
    interval: 21100
    path: /srv/disk1/debian-security
    name: debian-security
    <<: *oneshot_common
  # deepin
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.deepin.com/deepin/
    interval: 21900
    path: /srv/disk1/deepin
    name: deepin
    <<: *oneshot_common
  # deepin-cd
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.deepin.com/cdimage/
    interval: 22900
    path: /srv/disk1/deepin-cd
    name: deepin-cd
    <<: *oneshot_common
  # docker-ce
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.tuna.tsinghua.edu.cn/docker-ce/
    interval: 86400
    path: /srv/disk1/docker-ce
    name: docker-ce
    <<: *oneshot_common
  # fedora/linux
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://download-ib01.fedoraproject.org/fedora-enchilada/linux/
    interval: 21600
    path: /srv/disk1/fedora/linux
    name: fedora/linux
    rsync_extra_flags: --exclude "development/*" --exclude "extras/*" --exclude "*/debug/*"
    <<: *oneshot_common
  # fedora/epel
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/fedora-epel/
    interval: 22600
    path: /srv/disk1/fedora/epel
    name: fedora/epel
    rsync_extra_flags: --exclude "development/*" --exclude "extras/*" --exclude "*/debug/*"
    <<: *oneshot_common
  # fedora-secondary
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/fedora-secondary/
    interval: 23600
    path: /srv/disk1/fedora-secondary
    name: fedora-secondary
    rsync_extra_flags: --exclude "development/*" --exclude "extras/*" --exclude "*/debug/*"
    <<: *oneshot_common
  # linuxmint
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/linuxmint-packages/
    interval: 22600
    path: /srv/disk1/linuxmint
    name: linuxmint
    <<: *oneshot_common
  # linuxmint-cd
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/linuxmint/
    interval: 21000
    path: /srv/disk1/linuxmint-cd
    name: linuxmint-cd
    <<: *oneshot_common
  # mageia
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.kernel.org/mageia/
    interval: 21200
    path: /srv/disk2/mageia
    name: mageia
    rsync_extra_flags: --exclude "*/devel/*"
    <<: *oneshot_common
  # opensuse
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://fr2.rpmfind.net/linux/opensuse/
    interval: 44200 # may be wrong
    rsync_extra_flags: --exclude "history/" --exclude "source/" --exclude "debug/"
    path: /srv/disk1/opensuse
    name: opensuse
    <<: *oneshot_common
  # openvz
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://download.openvz.org/openvz-download
    interval: 43600 # may be wrong
    path: /srv/disk2/openvz
    name: openvz
    <<: *oneshot_common
  # remi
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://remi.mirror.karneval.cz/remi
    interval: 43000
    path: /srv/disk2/remi
    name: remi
    <<: *oneshot_common
  # scientific
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirror.aarnet.edu.au/pub/scientific/
    interval: 21600 # may be wrong
    path: /srv/disk2/scientific
    name: scientific
    rsync_extra_flags: --exclude "*/obsolete/*" --exclude "obsolete"
    <<: *oneshot_common
  #ubuntu
  - type: shell_script
    script: /worker-script/ubuntu-debian-rsync.sh
    source: rsync://archive.ubuntu.com/ubuntu/
    interval: 24900
    path: /srv/disk2/ubuntu
    name: ubuntu
    no_redir_http: true
    <<: *oneshot_common
  # ubuntu-cd
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://rsync.releases.ubuntu.com/releases/
    interval: 24600
    path: /srv/disk2/ubuntu-cd
    name: ubuntu-cd
    <<: *oneshot_common
  # ubuntu-cdimage
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://cdimage.ubuntu.com/cdimage/
    interval: 24900
    path: /srv/disk2/ubuntu-cdimage
    name: ubuntu-cdimage
    <<: *oneshot_common
  # ubuntu-ports
  - type: shell_script
    script: /worker-script/rsync.sh
    source: rsync://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports
    interval: 31000
    path: /srv/disk2/ubuntu-ports
    name: ubuntu-ports
    <<: *oneshot_common
