[default]
address = "0.0.0.0"
concurrent_download = 16
max_pending_task = 65536
user_agent = "mirror-intel / 0.1 (siyuan.internal.sjtug.org)"
file_threshold_mb = 20
ignore_threshold_mb = 4096
base_url = "https://mirrors.sjtug.sjtu.edu.cn"
ttl = 3
direct_stream_size_kb = 4
read_only = false
log_level = "off"
download_timeout = 60
workers = 8

[default.endpoints]
rust_static = "https://static.rust-lang.org"
homebrew_bottles = "https://homebrew.bintray.com"
linuxbrew_bottles = "https://linuxbrew.bintray.com"
pypi_packages = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages"
fedora_iot = "https://d2ju0wfl996cmc.cloudfront.net"
fedora_ostree = "https://d2uk5hbyrobdzx.cloudfront.net"
flathub = "https://dl.flathub.org/repo"
crates_io = "https://static.crates.io"
dart_pub = "https://pub.dartlang.org"
guix = "https://ci.guix.gnu.org"
pytorch_wheels = "https://download.pytorch.org/whl"
sjtug_internal = "https://github.com/sjtug"
flutter_infra = "https://storage.googleapis.com/flutter_infra"

[default.s3]
endpoint = "https://s3.jcloud.sjtu.edu.cn"
bucket = "899a892efef34b1b944a19981040f55b-oss01"
