[default]
address = "0.0.0.0"
base_url = "https://mirror.sjtu.edu.cn"
concurrent_download = 16
direct_stream_size_kb = 4
download_timeout = 300
file_threshold_mb = 20
ignore_threshold_mb = 4096
log_level = "off"
max_pending_task = 65536
read_only = false
ttl = 3
user_agent = "mirror-intel / 0.1 (mirror.sjtu.edu.cn)"
workers = 8

[default.github_release]
allow = [
  "FreeCAD/FreeCAD/",
  "prometheus/prometheus/",
  "prometheus/node_exporter/",
  "prometheus/alertmanager/",
  "prometheus/blackbox_exporter/",
  "prometheus/consul_exporter/",
  "prometheus/graphite_exporter/",
  "prometheus/haproxy_exporter/",
  "prometheus/memcached_exporter/",
  "prometheus/mysqld_exporter/",
  "prometheus/pushgateway/",
  "prometheus/statsd_exporter/",
  "GNS3/gns3-gui/",
  "PowerShell/PowerShell/",
  "oneclick/rubyinstaller2/",
  "mikefarah/yq/"
]

[default.endpoints]
crates_io = "https://static.crates.io"
dart_pub = "https://pub.dartlang.org"
fedora_iot = "https://d2ju0wfl996cmc.cloudfront.net"
fedora_ostree = "https://d2uk5hbyrobdzx.cloudfront.net"
flathub = "https://dl.flathub.org/repo"
flutter_infra = "https://storage.flutter-io.cn/flutter_infra"
github_release = "https://github.com"
guix = "https://ci.guix.gnu.org"
homebrew_bottles = "https://homebrew.bintray.com"
linuxbrew_bottles = "https://linuxbrew.bintray.com"
nix_channels_store = "https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store"
pypi_packages = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages"
pytorch_wheels = "https://download.pytorch.org/whl"
rust_static = "https://static.rust-lang.org"
sjtug_internal = "https://github.com/sjtug"
overrides = [
  { name = "flutter", pattern = "https://storage.flutter-io.cn/", replace = "https://storage.googleapis.com/" },
  { name = "tuna", pattern = "https://mirrors.tuna.tsinghua.edu.cn/", replace = "https://nanomirrors.tuna.tsinghua.edu.cn/" }
]

[default.s3]
bucket = "899a892efef34b1b944a19981040f55b-oss01"
endpoint = "https://s3.jcloud.sjtu.edu.cn"
