name: Test Caddy Config
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose build
        run: docker-compose build
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - uses: dschep/install-pipenv-action@v1
      - name: check if Caddyfile is latest version
        run: make caddy-gen && git diff --exit-code
      - name: check Caddyfile format
        run: make caddy-format-config && git diff --exit-code
      - name: verify Caddyfile format
        run: make caddy-verify-config
