name: Lint and Validation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-lug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i -g prettier
      - run: prettier -c lug/*.yaml
  test-docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mirror: ["siyuan", "zhiyuan"]
    steps:
      - uses: actions/checkout@v2
      - name: use CI config for docker-compose
        run: |
          cp docker-compose.ci.yml docker-compose.override.yml 
          cp .env.ci .env
          cp ./secrets/caddy.env.example ./secrets/caddy.env
          cp ./secrets/mirror-intel.env.example ./secrets/mirror-intel.env
          cp ./secrets/gcr-registry.ci.yml ./secrets/gcr-registry.yml
          cp ./secrets/docker-registry.ci.yml ./secrets/docker-registry.yml
      - run: docker-compose pull
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: verify config
        run: docker-compose -f docker-compose.yml -f docker-compose.${{ matrix.mirror }}.yml config
      - name: docker-compose build
        run: docker-compose -f docker-compose.yml -f docker-compose.${{ matrix.mirror }}.yml -f docker-compose.ci.yml build --parallel
      - name: validate Caddyfile
        run: make caddy-verify-config
  test-caddy-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - uses: dschep/install-pipenv-action@v1
      - name: setup Pipenv
        run: cd caddy-gen && pipenv install
      - name: check if Caddyfile is latest version
        run: make caddy-gen && git diff --exit-code
